.TH ppick 1 "2022" "version 1.0.0" "USER COMMANDS"

.SH NAME
.B ppick
\-- a simple, curses-based interactive utility for picking one of a number of things at the terminal

.SH SYNOPSIS
tpick [OPTIONS...] THING [THINGS...]
.PP
tpick -i [OPTIONS...]
.PP
tpick -i [OPTIONS...] COMMAND [ARGUMENTS...]
.SH DESCRIPTION
.PP
ppick is a simple, curses-based interactive utility for picking one of a number
of things.  If one or more THINGS are provided on the command line, then ppick
interactively picks one of them.  Otherwise, ppick reads lines from standard
input and offers them for picking.

To pick something, just start typing characters; only entries containing those characters are displayed.
Matching is smartcase, and uses fnmatch(3).

Use ENTER to exit, writing the selected element (the one at the top of the
list) to standard output.  You can also exit (and fail) using either ESCAPE,
Control-C or qq.  You never search for two consecutive q characters,
right?

.SH OPTIONS

.TP
-i
read things from standard input (one per line), instead of from the command line

.TP
-i [OPTIONS] COMMAND [ARGUMENTS...]
read things from standard input, and execute the indicated command with the selected thing as an additional argument

.TP
-p TEXT
prepend TEXT to the fnmatch pattern (the default is "*")

.TP
-s TEXT
append TEXT to the fnmatch pattern (the default is "*")

.TP
-P
do not prepend anything to the fnmatch pattern

.TP
-S
do not append anything to the fnmatch pattern

.TP
-f TEXT
set your favourite text; then, hitting the ";" key adds your favourite text to the current query

.TP
-Q
disable the feature whereby two consecutive q characters exits

.TP
-h
output a help message

.SH SEE ALSO

ppick is very similar to tpick, just with different scrolling and much faster screen updates. tpick is similar to slmenu(1), and is also similar to dmenu(1) (although for the terminal, of course).

.SH EXIT STATUS
ppick yields an exit status of 0 if a thing was successfully picked, and something else otherwise.

.SH AUTHOR
Alan Robinson (https://github.com/alanbork/ppick); ppick is heavily based on tpick by Stephen Blott.


